apiVersion: batch/v1
kind: Job
metadata:
  name: app
  labels:
    app: debug
spec:
  template:
    spec:
      containers:
        - name: app
          image: busybox
          command:
            - /bin/sh
            - -c
            - echo "Hello Kubernetes!"
      restartPolicy: Never
  backoffLimit: 1
