kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/var/lib/kubernetes/ca.pem"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"

#: dns for kubernetes service discovery, consider that this ns
#: entry would be exposed to container's /etc/resolve.conf file
clusterDNS:
  - "178.79.168.130"
  # - "10.32.0.10"

#: 5 days before running garbage collection upon images
imageMinimumGCAge: "120h"
resolvConf: "/etc/resolv.conf"
runtimeRequestTimeout: "15m"

#: don't forget to change certificate paths according to your node
#: placements. i.e. after copying this config file to node-2 consider
#: changing certificates
tlsCertFile: "/var/lib/kubernetes/kubelet/node-1.pem"
tlsPrivateKeyFile: "/var/lib/kubernetes/kubelet/node-1-key.pem"

#: Resourced that would be reserved by system, i.e. this amount of
#: resources would be subtracted from available resource set for kubernetes
#: environment
systemReserved:
    cpu: 200m
    memory: 600Mi
