apiVersion: v1
kind: Secret
metadata:
  labels:
    app: example
  name: backend
  namespace: example
data:
  DATABASE_PASSWORD: "<base64 encoded password>"
  EMAIL_HOST_PASSWORD: "<base64 encoded email password>"
